spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka